/* Duplicate the fd of a file auto generated by the OS */
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>

int main() {
    char* filename = "new_file.txt";
    int file_fd = open(filename, O_RDONLY | O_CREAT);
    printf("fd of file is: %d\n", file_fd);
    int duplicate_fd = dup(file_fd);
    printf("duplicate fd of the given file: %d\n", duplicate_fd);
}
